# 1. Impor Library

In [1]:
#mengimpor library yang diperlukan
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

# 2. Baca Dataset

In [2]:
#membaca dataset
df=pd.read_csv('https://raw.githubusercontent.com/yyunitasa-stack/Amazon-E-Commerce-Sales-Performance-Analysis/main/Dataset/Amazon%20Sale%20Report.csv')

C:\Users\YUNITA\AppData\Local\Temp\ipykernel_13556\1976285538.py:2: DtypeWarning: Columns (0: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('https://raw.githubusercontent.com/yyunitasa-stack/Amazon-E-Commerce-Sales-Performance-Analysis/main/Dataset/Amazon%20Sale%20Report.csv')

# 3. Data Inspection

In [3]:
#menampilkan 5 data teratas
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [4]:
#memeriksa ukuran dataset
df.shape
#Interpretasi: Dataset memiliki 128.975 baris dan 10 kolom

(128975, 24)

In [5]:
#memeriksa informasi dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  str
 2   Date                128975 non-null  str
 3   Status              128975 non-null  str
 4   Fulfilment          128975 non-null  str
 5   Sales Channel       128975 non-null  str
 6   ship-service-level  128975 non-null  str
 7   Style               128975 non-null  str
 8   SKU                 128975 non-null  str
 9   Category            128975 non-null  str
 10  Size                128975 non-null  str
 11  ASIN                128975 non-null  str
 12  Courier Status      122103 non-null  str
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  str
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  str
 17  ship-state          128942 non-null  str
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  str
 20  promotion-ids       79822 non-null   str
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   str
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(1), str(18)
memory usage: 22.8+ MB

In [6]:
#menampilkan statistik deskriptif dari dataset
df.describe()

               index            Qty         Amount  ship-postal-code
count  128975.000000  128975.000000  121180.000000     128942.000000
mean    64487.000000       0.904431     648.561465     463966.236509
std     37232.019822       0.313354     281.211687     191476.764941
min         0.000000       0.000000       0.000000     110001.000000
25%     32243.500000       1.000000     449.000000     382421.000000
50%     64487.000000       1.000000     605.000000     500033.000000
75%     96730.500000       1.000000     788.000000     600024.000000
max    128974.000000      15.000000    5584.000000     989898.000000

# 4. Data Preparation

## 4.1 Column & Data Type

In [7]:
#memeriksa nama-nama kolom
print(df.columns.tolist())
#Interpetasi: terdapat whitespace pada nama kolom Sales Channel
#Interpretasi: nama kolom tidak konsisten (kapital dan kecil) sehingga perlu diatasi

['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ', 'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN', 'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city', 'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids', 'B2B', 'fulfilled-by', 'Unnamed: 22']

In [8]:
#mengatasi nama kolom yang tidak konsisten dan mengandung whitespace
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','-')
df = df.rename(columns={
    'sales-channel-': 'sales-channel',
    'sku': 'SKU',
    'asin': 'ASIN',
    'b2b': 'B2B',
    'unnamed:-22':'unnamed:22'
})

In [9]:
#menampilkan 5 data teratas
df.head()
#Interpretasi: Kolom currency, ship-country, fulfilled-by, dan unnamed:22 memiliki nilai yang konstan sehingga tidak memiliki arti analisis
#Interpretasi: Kolom index memiliki nilai yang unik sehingga tidak memiliki arti analisis

,index,order-id,date,status,fulfilment,sales-channel,ship-service-level,style,SKU,category,...,currency,amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,unnamed:22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [10]:
#menghapus kolom konstan dan kolom yang tidak memiliki arti analisis
df.drop(['index','currency','ship-country','fulfilled-by','unnamed:22'],axis=1,inplace=True)

In [11]:
#memeriksa tipe data dari setiap kolom
df.dtypes
#Interpretasi: Tipe data date adalah string, sehingga perlu diubah menjadi tipe data datetime agar dapat dilakukan analisis berbasis waktu
#Interpretasi: Tipe data ship-postal-code adalah float, sehingga perlu diubah menjadi tipe data string/object karena berfungsi sebagai kode atau identitas

order-id                  str
date                      str
status                    str
fulfilment                str
sales-channel             str
ship-service-level        str
style                     str
SKU                       str
category                  str
size                      str
ASIN                      str
courier-status            str
qty                     int64
amount                float64
ship-city                 str
ship-state                str
ship-postal-code      float64
promotion-ids             str
B2B                      bool
dtype: object

In [12]:
#menangani kolom date dengan mengubah menjadi tipe data datetime
df['date'] = pd.to_datetime(
    df['date'],
    format='%m-%d-%y',
    errors='coerce'
)
#menangani kolom ship-postal-code dengan mengubah menjadi tipe data string/object
df['ship-postal-code']=df['ship-postal-code'].astype(str)

## 4.2 Data Quality Check

### a. Nilai Tidak Konsisten dan Whitespace

In [13]:
#memeriksa data yang tidak konsisten pada variabel status
df['status'].value_counts()
#interpretasi: tidak ada data pada variabel Status yang tidak konsisten

status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [14]:
#memeriksa data yang tidak konsisten pada variabel Fulfilment
df['fulfilment'].value_counts()
#interpretasi: tidak ada data yang tidak konsisten

fulfilment
Amazon      89698
Merchant    39277
Name: count, dtype: int64

In [15]:
#memeriksa data yang tidak konsisten pada variabel Sales Channel
df['sales-channel'].value_counts()
#interpretasi: tidak ada data yang tidak konsisten

sales-channel
Amazon.in     128851
Non-Amazon       124
Name: count, dtype: int64

In [16]:
#memeriksa data yang tidak konsisten pada variabel ship-service-level
df['ship-service-level'].value_counts()
#interpretasi: tidak ada data yang tidak konsisten

ship-service-level
Expedited    88615
Standard     40360
Name: count, dtype: int64

In [17]:
#memeriksa data yang tidak konsisten pada variabel ship-service-level
df['category'].value_counts()
#interpretasi: tidak ada data yang tidak konsisten

category
Set              50284
kurta            49877
Western Dress    15500
Top              10622
Ethnic Dress      1159
Blouse             926
Bottom             440
Saree              164
Dupatta              3
Name: count, dtype: int64

In [18]:
#memeriksa data yang tidak konsisten pada variabel size
df['size'].value_counts()
#interpretasi: tidak ada data yang tidak konsisten

size
M       22711
L       22132
XL      20876
XXL     18096
S       17090
3XL     14816
XS      11161
6XL       738
5XL       550
4XL       427
Free      378
Name: count, dtype: int64

In [19]:
#memeriksa data yang tidak konsisten pada variabel Courier Status
df['courier-status'].value_counts()
#interpretasi: tidak ada data yang tidak konsisten

courier-status
Shipped      109487
Unshipped      6681
Cancelled      5935
Name: count, dtype: int64

In [20]:
#memeriksa data yang tidak konsisten pada variabel ship-city
df['ship-city'].value_counts()
#interpretasi: kolom ship-city memiliki banyak data yang salah sehingga perlu dihapus

ship-city
BENGALURU                    11217
HYDERABAD                     8074
MUMBAI                        6126
NEW DELHI                     5795
CHENNAI                       5421
                             ...
VARANASIVaranasi                 1
Cherukunnu (p.o)                 1
GULABPURA, Distt BHILWARA        1
Prayagraj (ALLAHABAD)            1
Halol                            1
Name: count, Length: 8955, dtype: int64

In [21]:
#memeriksa data yang tidak konsisten pada variabel ship-state
df['ship-state'].value_counts()
#interpretasi: terdapat data yang tidak konsisten

ship-state
MAHARASHTRA      22260
KARNATAKA        17326
TAMIL NADU       11483
TELANGANA        11330
UTTAR PRADESH    10638
                 ...
Nagaland             1
bihar                1
Mizoram              1
rajsthan             1
Rajsthan             1
Name: count, Length: 69, dtype: int64

In [22]:
#memeriksa data yang tidak konsisten pada variabel promotion-ids
df['promotion-ids'].value_counts()
#interpretasi: kolom promotion-ids memiliki banyak data yang salah dan merupakan kolom yang tidak memiliki arti analisis sehingga perlu dihapus

promotion-ids
IN Core Free Shipping 2015/04/08 23-48-5-108                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               46100
Duplicated A12RHGVGRWOT3S 1560498941486                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      489
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-XX7G3ZRJJJ5LG,Amazon PLCC Free-Financing Universal Merchant AAT-LEHCKNDBJG64E,Amazon PLCC Free-Financing Universal Merchant AAT-DJVHCEV7D7RQY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                       458
Duplicated AYTJSBA8ZOP16 1567159860988                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       433
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                       316
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ...
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-EWAPBB6BDRGM6,Amazon PLCC Free-Financing Universal Merchant AAT-R7GXNZWISTRFA,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-5ZEB2OGNZ32MC,Amazon PLCC Free-Financing Universal Merchant AAT-NT3ZJJGQ3JK3Q,Amazon PLCC Free-Financing Universal Merchant AAT-5SHH3G55USK5C,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                         1
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-EWAPBB6BDRGM6,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,VPC-44571-38708638 Coupon,Amazon PLCC Free-Financing Universal Merchant AAT-5ZEB2OGNZ32MC,Amazon PLCC Free-Financing Universal Merchant AAT-NT3ZJJGQ3JK3Q,Amazon PLCC Free-Financing Universal Merchant AAT-5SHH3G55USK5C,Amazon PLCC Free-Financing Universal Merchant AAT-TNYBHEAO7HOHO,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4,Amazon PLCC Free-Financing Universal Merchant AAT-QMFZ3M7T5NPDS,Amazon PLCC Free-Financing Universal Merchant #MP-pmilan-1601980554292        1
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-SL3Y2YRMAUNFC,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-EWAPBB6BDRGM6,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-5ZEB2OGNZ32MC,Amazon PLCC Free-Financing Universal Merchant AAT-NT3ZJJGQ3JK3Q,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                         1
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-SL3Y2YRMAUNFC,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-EWAPBB6BDRGM6,Amazon PLCC Free-Financing Universal Merchant AAT-R7GXNZWISTRFA,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-5ZEB2OGNZ32MC,Amazon PLCC Free-Financing Universal Merchant AAT-NT3ZJJGQ3JK3Q,Amazon PLCC Free-Financing Universal Merchant AAT-5SHH3G55USK5C,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                         1
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-EWAPBB6BDRGM6,Amazon PLCC Free-Financing Universal Merchant AAT-R7GXNZWISTRFA,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-NT3ZJJGQ3JK3Q,Amazon PLCC Free-Financing Universal Merchant AAT-5SHH3G55USK5C,Amazon PLCC Free-Financing Universal Merchant AAT-TNYBHEAO7HOHO,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4,Amazon PLCC Free-Financing Universal Merchant AAT-QMFZ3M7T5NPDS,Amazon PLCC Free-Financing Universal Merchant #MP-pmilan-1601980554292                                  1
Name: count, Length: 5787, dtype: int64

### b. Nilai Tidak Valid

In [23]:
#memeriksa invalid values pada setiap kolom numerik
df.describe()
#Interpretasi: tidak terdapat invalid values pada setiap kolom numerik

                             date            qty         amount
count                      128975  128975.000000  121180.000000
mean   2022-05-12 11:49:27.951929       0.904431     648.561465
min           2022-03-31 00:00:00       0.000000       0.000000
25%           2022-04-20 00:00:00       1.000000     449.000000
50%           2022-05-10 00:00:00       1.000000     605.000000
75%           2022-06-04 00:00:00       1.000000     788.000000
max           2022-06-29 00:00:00      15.000000    5584.000000
std                           NaN       0.313354     281.211687

### c. Duplicate Data

In [24]:
#menampilkan duplicate data
df.duplicated().sum()
#interpretasi: terdapat 6 data duplikat

np.int64(6)

In [25]:
#memeriksa setiap baris yang memiliki duplikat
df[df.duplicated(keep=False)]

,order-id,date,status,fulfilment,sales-channel,ship-service-level,style,SKU,category,size,ASIN,courier-status,qty,amount,ship-city,ship-state,ship-postal-code,promotion-ids,B2B
30660,406-0372545-6086735,2022-04-12,Cancelled,Amazon,Amazon.in,Expedited,SET197,SET197-KR-NP-L,Set,L,B08B3YPD63,Cancelled,0,NaN,Siliguri,WEST BENGAL,734008.0,NaN,False
30661,406-0372545-6086735,2022-04-12,Cancelled,Amazon,Amazon.in,Expedited,SET197,SET197-KR-NP-L,Set,L,B08B3YPD63,Cancelled,0,NaN,Siliguri,WEST BENGAL,734008.0,NaN,False
41291,408-0373839-4433120,2022-04-05,Cancelled,Amazon,Amazon.in,Expedited,JNE3501,JNE3501-KR-M,kurta,M,B08MYVCDB4,Cancelled,0,NaN,BENGALURU,KARNATAKA,560072.0,NaN,False
41292,408-0373839-4433120,2022-04-05,Cancelled,Amazon,Amazon.in,Expedited,JNE3501,JNE3501-KR-M,kurta,M,B08MYVCDB4,Cancelled,0,NaN,BENGALURU,KARNATAKA,560072.0,NaN,False
79844,171-9628368-5329958,2022-05-07,Cancelled,Amazon,Amazon.in,Expedited,J0329,J0329-KR-L,kurta,L,B09KXRB7JV,Cancelled,0,NaN,ERNAKULAM,KERALA,682017.0,NaN,False
79845,171-9628368-5329958,2022-05-07,Cancelled,Amazon,Amazon.in,Expedited,J0329,J0329-KR-L,kurta,L,B09KXRB7JV,Cancelled,0,NaN,ERNAKULAM,KERALA,682017.0,NaN,False
85790,171-3249942-2207542,2022-05-03,Shipped,Amazon,Amazon.in,Expedited,SET323,SET323-KR-NP-XL,Set,XL,B09NDKKM7P,Shipped,1,939.0,PUNE,MAHARASHTRA,411057.0,IN Core Free Shipping 2015/04/08 23-48-5-108,False
85791,171-3249942-2207542,2022-05-03,Shipped,Amazon,Amazon.in,Expedited,SET323,SET323-KR-NP-XL,Set,XL,B09NDKKM7P,Shipped,1,939.0,PUNE,MAHARASHTRA,411057.0,IN Core Free Shipping 2015/04/08 23-48-5-108,False
86418,405-8669298-3850736,2022-05-03,Shipped,Amazon,Amazon.in,Expedited,MEN5025,MEN5025-KR-XXXL,kurta,3XL,B08YYQS8FH,Shipped,1,533.0,GHAZIABAD,UTTAR PRADESH,201010.0,IN Core Free Shipping 2015/04/08 23-48-5-108,False
86419,405-8669298-3850736,2022-05-03,Shipped,Amazon,Amazon.in,Expedited,MEN5025,MEN5025-KR-XXXL,kurta,3XL,B08YYQS8FH,Shipped,1,533.0,GHAZIABAD,UTTAR PRADESH,201010.0,IN Core Free Shipping 2015/04/08 23-48-5-108,False
98954,407-4853873-4978725,2022-06-22,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-M,Set,M,B08XNJG8B1,Shipped,1,1163.0,Zirakpur,Punjab,140603.0,IN Core Free Shipping 2015/04/08 23-48-5-108,False
98955,407-4853873-4978725,2022-06-22,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-M,Set,M,B08XNJG8B1,Shipped,1,1163.0,Zirakpur,Punjab,140603.0,IN Core Free Shipping 2015/04/08 23-48-5-108,False

### d. Missing Value

In [26]:
#memeriksa missing value pada dataset
df.isnull().sum()
#interpretasi: kolom courier-status, amount, ship-city, ship-state, ship-postal-code, promotion-ids memiliki missing value

order-id                  0
date                      0
status                    0
fulfilment                0
sales-channel             0
ship-service-level        0
style                     0
SKU                       0
category                  0
size                      0
ASIN                      0
courier-status         6872
qty                       0
amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
promotion-ids         49153
B2B                       0
dtype: int64

In [27]:
#memeriksa persentase missing value
df.isnull().sum()/df.shape[0]*100
#Interpretasi: kolom ship-city, ship-state, ship-posta-code, dan ship-country memiliki missing value kurang dari 5% (<5%), sehingga baris berisi missing value bisa langsung dihapus (drop)
#Interpretasi: kolom promotion-ids memiliki banyak missing value (38,1%), sehingga perlu dihapus

order-id               0.000000
date                   0.000000
status                 0.000000
fulfilment             0.000000
sales-channel          0.000000
ship-service-level     0.000000
style                  0.000000
SKU                    0.000000
category               0.000000
size                   0.000000
ASIN                   0.000000
courier-status         5.328164
qty                    0.000000
amount                 6.043807
ship-city              0.025586
ship-state             0.025586
ship-postal-code       0.025586
promotion-ids         38.110487
B2B                    0.000000
dtype: float64

In [28]:
#menampilkan detail baris dan kolom missing value
df[df.isnull().any(axis=1)]

,order-id,date,status,fulfilment,sales-channel,ship-service-level,style,SKU,category,size,ASIN,courier-status,qty,amount,ship-city,ship-state,ship-postal-code,promotion-ids,B2B
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,NaN,0,647.62,MUMBAI,MAHARASHTRA,400081.0,NaN,False
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,NaN,0,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,NaN,False
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,B098714BZP,Shipped,1,574.00,CHENNAI,TAMIL NADU,600073.0,NaN,False
8,407-5443024-5233168,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,3XL,B08L91ZZXN,Cancelled,0,NaN,HYDERABAD,TELANGANA,500008.0,IN Core Free Shipping 2015/04/08 23-48-5-108,False
9,402-4393761-0311520,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3461,JNE3461-KR-XXL,kurta,XXL,B08B3XF5MH,Shipped,1,363.00,Chennai,TAMIL NADU,600041.0,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128966,406-9812666-2474761,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,SET224,SET224-KR-NP-XS,Set,XS,B08MXDBRK1,Shipped,1,1132.00,CHENNAI 600042,TAMIL NADU,600042.0,NaN,False
128967,404-5182288-1653947,2022-05-31,Cancelled,Amazon,Amazon.in,Expedited,JNE3638,JNE3638-KR-XS,kurta,XS,B09814Q3QH,Cancelled,0,NaN,Kolkata,WEST BENGAL,700040.0,NaN,False
128969,404-3802633-7250760,2022-05-31,Cancelled,Amazon,Amazon.in,Expedited,SET044,SET044-KR-NP-M,Set,M,B07Q2RTSFB,Unshipped,1,612.00,MUMBAI,MAHARASHTRA,400017.0,NaN,False
128970,406-6001380-7673107,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,XL,B098112V2V,Shipped,1,517.00,HYDERABAD,TELANGANA,500013.0,NaN,False
128972,407-9547469-3152358,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,XXL,B0982YZ51B,Shipped,1,690.00,HYDERABAD,TELANGANA,500049.0,NaN,False

## 4.3 Data Cleaning

### a. Mengatasi Nilai Tidak Konsisten

In [29]:
#mengatasi data tidak konsisten
df['ship-state']=df['ship-state'].str.upper()
df['ship-state'] = df['ship-state'].replace({
    'ORISSA': 'ODISHA',
    'RJ': 'RAJASTHAN',
    'RAJSHTHAN': 'RAJASTHAN',
    'RAJSTHAN': 'RAJASTHAN',
    'NL': 'NAGALAND',
    'PUNJAB/MOHALI/ZIRAKPUR': 'PUNJAB',
    'PB': 'PUNJAB',
    'APO': 'ANDHRA PRADESH',
    'AR': 'ARUNACHAL PRADESH',
    'PONDICHERRY': 'PUDUCHERRY',
    'NEW DELHI': 'DELHI'
})
#menghapus kolom ship-city, karena banyak nilai yang salah pada kolom tersebut
df.drop(['ship-city'],axis=1,inplace=True)
#menghapus kolom promotion-ids, karena banyak nilai yang salah dan merupakan kolom yang tidak memiliki arti analisis
df.drop(['promotion-ids'],axis=1,inplace=True)

### b. Mengatasi Duplicate Data

In [30]:
#mengatasi data duplikat dengan menghapus salah satu baris duplikat
df.drop_duplicates(inplace=True)

### c. Mengatasi Missing Value

In [31]:
#menghapus baris yang berisi missing value <5% (ship-city)
df=df.dropna(subset=['ship-state','ship-postal-code'])
#mengatasi missing value dengan mengisi menggunakan modus pada kolom Courier Status
df['courier-status']=df['courier-status'].fillna(df['courier-status'].mode()[0])
#mengatasi missing value dengan mengisi menggunakan median pada kolom Amount
df['amount']=df['amount'].fillna(df['amount'].median())

## 4.4 Data Validation

In [32]:
#memeriksa kembali kolom dan tipe data
df.dtypes
#Interpretasi: nama kolom dan tipe data masing-masing kolom sudah sesuai

order-id                         str
date                  datetime64[us]
status                           str
fulfilment                       str
sales-channel                    str
ship-service-level               str
style                            str
SKU                              str
category                         str
size                             str
ASIN                             str
courier-status                   str
qty                            int64
amount                       float64
ship-state                       str
ship-postal-code                 str
B2B                             bool
dtype: object

In [33]:
#memeriksa kembali data konsisten
df['ship-state'].value_counts()
#data sudah konsisten

ship-state
MAHARASHTRA           22259
KARNATAKA             17325
TAMIL NADU            11483
TELANGANA             11330
UTTAR PRADESH         10637
DELHI                  7048
KERALA                 6584
WEST BENGAL            5962
ANDHRA PRADESH         5431
GUJARAT                4489
HARYANA                4415
RAJASTHAN              2718
MADHYA PRADESH         2529
ODISHA                 2139
BIHAR                  2114
PUNJAB                 1918
ASSAM                  1663
UTTARAKHAND            1553
JHARKHAND              1456
GOA                    1137
CHHATTISGARH            909
HIMACHAL PRADESH        788
JAMMU & KASHMIR         702
PUDUCHERRY              351
CHANDIGARH              333
MANIPUR                 316
ANDAMAN & NICOBAR       257
MEGHALAYA               207
SIKKIM                  205
NAGALAND                187
TRIPURA                 151
ARUNACHAL PRADESH       147
MIZORAM                  76
DADRA AND NAGAR          70
LADAKH                   43
LAKSHADWEEP               4
Name: count, dtype: int64

In [34]:
#memeriksa kembali data duplikat
df.duplicated().sum()
#data sudah tidak ada duplikat

np.int64(0)

In [35]:
#memeriksa kembali missing value
df.isnull().sum()
#data sudah tidak ada missing value

order-id              0
date                  0
status                0
fulfilment            0
sales-channel         0
ship-service-level    0
style                 0
SKU                   0
category              0
size                  0
ASIN                  0
courier-status        0
qty                   0
amount                0
ship-state            0
ship-postal-code      0
B2B                   0
dtype: int64

In [36]:
#menyimpan dataset yang sudah dibersihkan ke dalam file CSV
df.to_csv("C:/Users/YUNITA/Documents/GitHub/Amazon E Commerce Sales Performance Analysis/Dataset/Amazon Sale Report Cleaned.csv",index=False)